### ISSUE TITLE
[audio] C.2 Non-necessary files

### ISSUE THREAD

**Issue by lostanlen** [scatnet/scatnet#29]
Remove separate_freq.m, max_scat.m, and thresholded_wavelet_1d.m from the release, but keep a copy of them in a local drive.

**Comment by janden** [comment]
As it is right now, they are not in the release, which is kept in the 'release' branch.

**Comment by lostanlen** [comment]
I have updated the 'release' branch, moved some files to 'papers/*/' and removed 'experimental' files, e.g. joint scattering and thresholding.
