### ISSUE TITLE
Error in conv_sub_2d probably due to padding

### ISSUE THREAD

**Issue by edouardoyallon** [scatnet/scatnet#42]
Error message: 

[S,U]=scat(x,Wop);
Subscript indices must either be real positive integers or logicals.
Error in conv_sub_2d (line 11)
            x_conv_y = conv_sub_2d(xf, filter.coefft{res+1}, ds);

This is due to the line:
res = log2(size(filter.coefft{1},1)/size(xf,1));
which is not an integer anymore. This is probably due to the padding step.

**Comment by janden** [comment]
I got the same error. For some reason wavelet_2d sets all the meta fields to -1 for the psi outputs (lines 72-74). I commented them out locally and everything works. I think Laurent's in the middle of modifying the code, so I would let him handle it.
