### ISSUE TITLE
cellsrc2db...

### ISSUE THREAD

**Issue by janden** [scatnet/scatnet#54]
...is quite an obscure, undocumented function. Does it belong in /classification or /papers/RSDS, which is the only place it is used?

**Comment by janden** [comment]
Same goes for srcfun. Are these functions that general?

**Comment by laurentsifre** [comment]
Yep you can put it in rsds 

It converts a cell of features and a src to the right format db ready for classification hence its pretty self-explanatory name :)

I use this with srcfun and cellfun_monitor to bypass joakim pipeline :) when I want to apply several postprocessing without having to recompute the scattering each time

Envoyé de mon iPhone

**Comment by janden** [comment]
Well maybe that's a sign that the classification pipeline should be altered to allow such changes in post-processing, no? Well, maybe for version 0.3.

I'll move them though, for now.
