### ISSUE TITLE
inverse_scat efficiency

### ISSUE THREAD

**Issue by janden** [scatnet/scatnet#55]
Right now, the inverse_scat function works with unnecessarily high resolution, which increases computational complexity significantly and could introduce errors.

**Comment by pree1210** [comment]
can u please help me. How to reconstruct image using inverse_scat function after applying scattering transform. I m getting error the following error.

Error using griddedInterpolant
The grid vectors do not define a grid of points that match the given values.

Error in interp1 (line 191)
        F = griddedInterpolant(X,V,method);

Error in upsample (line 21)
    y = interp1([-length(x):2*length(x)-1].', ...

Error in inverse_scat (line 96)
    x_phi = upsample(S{m+1}.signal{p}, N);
