### ISSUE TITLE
Warning: Name is nonexistent or not a directory: \path\to\scatnet 

### ISSUE THREAD

**Issue by lyzhangjm** [scatnet/scatnet#62]
Hello, when add path (addpath /path/to/scatnet;  addpath_scatnet;), there are error:
Warning: Name is nonexistent or not a directory: \path\to\scatnet 
 I can't find the file of path.  how can I fix this error ?
 Thanks.

**Comment by lostanlen** [comment]
You should replace the placeholder 'path/to/scatnet' by the path in which you have put the package.

**Comment by eickenberg** [comment]
Interesting.  I sent this comment by email

> "path/to/scatnet" has to be replaced with the true location where you placed the software. Where did you copy it to after downloading it?

and it never arrived.

 has to be replaced with the true location where you placed the software. Where did you copy it to after downloading it?

**Comment by eickenberg** [comment]
"path/to/scatnet" has to be replaced with the true location where you
placed the software. Where did you copy it to after downloading it?
