### ISSUE TITLE
I want to use the wavelet scattering to fusion image, but I don't know how can I inverse transformation after fusion

### ISSUE THREAD

**Issue by strawberry1996** [scatnet/scatnet#67]
Hello
I want to use the wavelet scattering to fusion image, but I don't know how can I inverse transformation after fusion

**Comment by lostanlen** [comment]
Hello,
I see you're posting the same message on many wavelet transform packages at once, including scatnet, kymatio, and this one. Know that this is not a recommended way to reach for help: you are possibly pinging the same people with the same message, several times, which ends up filling our inboxes unncessarily. I am going to close this isse on scattering.m and scatnet, and leave it open on Kymatio while you clarify what you're asking.
