### ISSUE TITLE
I used scatnet toolkit in my paper

### ISSUE THREAD

**Issue by strawberry1996** [scatnet/scatnet#68]
I used scatnet toolkit in my paper, how can I quote it in my paper? How do I insert a reference? Thanks

**Comment by janden** [comment]
Hi @strawberry1996. Thank you for using our software. You can cite ScatNet as

Andén J., Sifre L., Mallat S., Kapoko M., Lostanlen V., Oyallon E. Scatnet. _Computer Software_. Available: http://www.di.ens.fr/data/software/scatnet/.

**Comment by lostanlen** [comment]
Hello @strawberry1996. See this Google Scholar entry:
https://scholar.google.com/scholar?cluster=16946158985812810049
