### ISSUE TITLE
Work with RGB images

### ISSUE THREAD

**Issue by AlbertoPresta** [scatnet/scatnet#69]
Hi to everyone! 
I am trying to build a classification algorithm with RGB images, but I can't manage to deal with different channels (what I want to do is to concatenate responses of three different channels).
Can you please help me?

**Comment by lostanlen** [comment]
Hello @AlbertoPresta, can you try passing every color channel separately and concatenating the outputs?
Also: consider working in YUV space, not RGB
Also: the team has switched to Python :) please visit: https://kymat.io
